name: todo_task_bloc
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.1
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: 2.0.9
  google_fonts: ^6.1.0
  persian_fonts: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
